IPv4dev=INTERFACE
IPv4addr=IPADDRESS
IPv4gw=GATEWAY
dhcpReserv=0
netvpnenableipv6=0
install_user=pi
VPN=openvpn
netvpnPROTO=udp
netvpnPORT=1194
netvpnDNS1=9.9.9.9
netvpnDNS2=149.112.112.112
netvpnHOST=netvpn.test
netvpnENCRYPT=256
netvpnSEARCHDOMAIN=netvpn.test
TWO_POINT_FIVE=1
USE_PREDEFINED_DH_PARAM=1
UNATTUPG=1
