IPv4dev=INTERFACE
IPv4addr=IPADDRESS
IPv4gw=GATEWAY
dhcpReserv=0
netvpnenableipv6=0
install_user=pi
VPN=wireguard
netvpnPORT=51820
netvpnDNS1=9.9.9.9
netvpnDNS2=149.112.112.112
netvpnHOST=pivpn.test
UNATTUPG=1
