IPv4dev=eth0
IPv6dev=eth0
install_user=pi
VPN=wireguard
pivpnNET=10.6.0.0
subnetClass=24
netvpnforceipv6route=1
netvpnorceipv6=0
netvpnenableipv6=1
netvpnNETv6="fd11:5ee:bad:c0de::"
subnetClassv6=64
ALLOWED_IPS="0.0.0.0/0, ::0/0"
netvpnMTU=1420
netvpnPORT=51820
netvpnDNS1=9.9.9.9
netvpnDNS2=149.112.112.112
netvpnHOST=pivpn.example.com
netvpnPERSISTENTKEEPALIVE=25
UNATTUPG=1
