IPv4dev=eth0
IPv4addr=192.168.23.211/24
IPv4gw=192.168.23.1
dhcpReserv=0
pivpnenableipv6=0
install_user=pi
VPN=openvpn
netvpnNET=10.8.0.0
subnetClass=24
netvpnPROTO=udp
netvpnPORT=1194
netvpnDNS1=9.9.9.9
netvpnDNS2=149.112.112.112
netvpnHOST=pivpn.example.com
netvpnENCRYPT=256
netvpnSEARCHDOMAIN=searchdomain.example.com
TWO_POINT_FIVE=1
USE_PREDEFINED_DH_PARAM=1
UNATTUPG=1
